from fastapi import APIRouter, Depends, HTTPException, status, Request
from ai.schemas import TravelPlanRequest, TravelPlanResponse
from ai import service
from auth.dependencies import get_current_user
from security.rate_limit import limiter
import logging

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/ai", tags=["AI Planner"])

@router.post(
    "/travel-plan",
    response_model=TravelPlanResponse,
    summary="Generate an AI-powered Eco Travel Plan",
)
@limiter.limit("3/minute")
async def create_travel_plan(
    request: Request,
    body: TravelPlanRequest,
    current_user: dict = Depends(get_current_user)
):
    """
    Takes user preferences and returns a personalized sustainable travel itinerary
    generated by the Google Gemini AI model.
    Rate limited to 3 requests per minute per IP to prevent quota abuse.
    """
    try:
        result = await service.generate_travel_plan(body.model_dump())
        return result
    except ValueError as ve:
        logger.error(f"AI Validation Error: {str(ve)}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(ve)
        )
    except RuntimeError as re:
        logger.error(f"AI Service Error: {str(re)}")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="The AI planning service is currently unavailable. Please try again later."
        )
    except Exception as e:
        logger.error(f"Unexpected Error in AI Planner: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An unexpected error occurred while generating your travel plan."
        )
